first commit
coderbabu10/Magical-Flute pull request #17
Opened 2019-12-09 11:47 UTC by atharvachavan2000

Button sizes were mismatched in tablet and smaller views. Adjusted those. Also added margin to make the buttons look aesthetically good.

2019-12-09 12:01 UTC, atharvachavan2000 commented
Resolved issue #16  and added the font awesome kit to the contact page. Added a link to the homepage.

2019-12-10 05:48 UTC, SuvamPrasd approved these changes

2019-12-10 18:47 UTC, atharvachavan2000 commented
Added Marquee tag as per the request in the Slack channel.

2019-12-11 08:00 UTC, SuvamPrasd requested changes
put the h1 style inside the h1 element itself.

2019-12-11 08:00 UTC, SuvamPrasd commented on param1.css
> +h1{
You can give this style inside the h1 element only.

2019-12-16 16:15 UTC, merged